default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: day3_development

test:
  <<: *default
  database: day3_test

production:
  <<: *default
  database: day3_production
  username: day3
  password: <%= ENV['DAY3_DATABASE_PASSWORD'] %>
